# Generated by Django 5.0.2 on 2024-11-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotifyData',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('nodename', models.CharField(default='India', max_length=255)),
                ('msgRecipients', models.TextField(default='no recipients')),
                ('msg', models.TextField(default='no message')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('nodename', models.CharField(max_length=255)),
                ('monsoonintensity', models.TextField(default='')),
                ('topographydrainage', models.TextField(default='')),
                ('rivermanagement', models.TextField(default='')),
                ('climatechange', models.TextField(default='')),
                ('siltation', models.TextField(default='')),
                ('drainagesystems', models.TextField(default='')),
                ('coastalvulnerability', models.TextField(default='')),
                ('watersheds', models.TextField(default='')),
                ('deterioratinginfrastructure', models.TextField(default='')),
                ('wetlandloss', models.TextField(default='')),
                ('predicttime', models.TextField(default='')),
                ('predictionclass', models.TextField(default='')),
                ('predictprobability', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
