# Generated by Django 5.0.2 on 2024-11-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsenseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgData',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('nodename', models.CharField(max_length=255)),
                ('imgBase64Text', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
