# Generated by Django 5.0.2 on 2024-11-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsenseapp', '0002_imgdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('ChatText', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackData',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('MsgText', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
