# Generated by Django 5.0.2 on 2024-11-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsenseapp', '0003_chatdata_feedbackdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdata',
            name='role',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
