# Generated by Django 5.0.2 on 2024-11-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsenseapp', '0005_reportedfloodalertdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqData',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
                ('Answer', models.TextField()),
            ],
        ),
    ]
