# Generated by Django 5.0.2 on 2024-11-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodsenseapp', '0006_faqdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='latitude',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='longitude',
            field=models.TextField(default=''),
        ),
    ]
